REM Relatório 1 de S01 - Matheus de Alencar Costa Oliveira - Matrícula: 456
0 PRINT "EXERCICIO 2 -- FATORIAL ALEATORIO"
10 LET N = RND(10)
20 PRINT "NUMERO ALEATORIO:"+N
30 LET FATORIAL = 1
40 FOR I = N TO 1 STEP -1
50 FATORIAL = FATORIAL * I
60 NEXT I
70 PRINT "FATORIAL DE " + N + ":" + FATORIAL